"""descriere asaa

Revision ID: 1522d9c0044f
Revises: e29f32235b84
Create Date: 2023-05-16 20:58:51.116394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1522d9c0044f'
down_revision = 'e29f32235b84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.drop_column('intro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intro', sa.VARCHAR(length=300), nullable=False))

    # ### end Alembic commands ###
