"""add image to autor

Revision ID: 66b11489c527
Revises: c38941e03213
Create Date: 2023-05-16 11:37:29.793839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b11489c527'
down_revision = 'c38941e03213'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
