"""descriere

Revision ID: 906ad48c67b8
Revises: c813c9bb402e
Create Date: 2023-05-16 20:05:53.127547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '906ad48c67b8'
down_revision = 'c813c9bb402e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descriere', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('descriere')

    # ### end Alembic commands ###
