"""Description of changes

Revision ID: c38941e03213
Revises: 
Create Date: 2023-05-16 01:24:45.027374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c38941e03213'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_nasterii', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('tara', sa.String(length=40), nullable=True))

    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('autor', schema=None) as batch_op:
        batch_op.drop_column('tara')
        batch_op.drop_column('data_nasterii')

    # ### end Alembic commands ###
