"""descriere asa

Revision ID: e29f32235b84
Revises: 906ad48c67b8
Create Date: 2023-05-16 20:09:11.086557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29f32235b84'
down_revision = '906ad48c67b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descr_carte', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carte', schema=None) as batch_op:
        batch_op.drop_column('descr_carte')

    # ### end Alembic commands ###
